import re

""" Paste your updated text here"""
text = """


* 1. [x] Computer Science [<CSE>]  
  * [x] General CS Content <gen_cse>                     - [compsci@lobsters]                           -[r/compsci,r/computerscience]  
  * [x] Theoretical Computer Science  [<tcse>]                                                             
    * [x] Distributed systems <distribut_sys>             - [distributed@lobsters]                     -[r/distributed]
    * [x] Data Structures <data_struct>                              - [gfg??,]                        -[r/datastructures]
    * [x] Algorithms <algo_dsa>                         - [gfg??,]                                     -[r/algorithms,r/cpp_questions]         
    * [@] Coding Philosophy
    * [x] Game Theory <gametheory>                                                                      -[r/GAMETHEORY]
    * [x] Discrete Mathematics <disco>                                                                 -[r/Discretemathematics]
    * [x] Cryptography(0)<crypto_cse>                  - [crypto@lobsters,]                            -[r/crypto,r/cryptography]
    * [x] Hardware   <hardware>                         - [hardware@lobsters]
    * [@] Parallel Programming
    * [@] Computability Theory
    * [x] Programming Language Theory <plt_cse>          - [plt@lobsters]
    * [x] Formal Methods  <frmlmeth_cse>                     - [formalmethods@@lobsters]
    * [x] CSE & Mathematic Logic  <logic>                - ........                                    -[r/logic]
  * 1.2. [x] ComputerEngineering [<ce>]
    * [x] Computer Architecture <comparch>                                                             -[r/computerarchitecture]
    * [x] Compilers <compiler>                           - [compilers@lobsters]                        -[r/compilers]
    * [x] Computer Network  <network>                     - [networking@lobsters]                       -[r/Network]
    * [x] Reverse Engineering <revengg>              - [reversing@lobsters,]                       -[r/ReverseEngineering]
    * [x] Operating Systems [<os>]
      * [x] OS Dev <osdev>                               - [osdev@lobsters]                            -[r/osdev]
      * [x] iOS <ios>                                 - [ios@lobsters]
      * [x] android <android>                         - [android@lobsters]                          -[r/Android]
      * [x] macOS <mac>                               - [mac@lobsters]                              -[r/MacOS,r/osx]
      * [x] windows <windows>                         - [windows@lobsters]                          -[r/windows]
      * [x] Linux  <linux>                            - [linux@lobsters]                            -[r/linux,r/kernel,r/linuxdev,r/linuxquestions,r/Ubuntu]
      * [x] Archlinux <archlinux>                                                                   -[r/archlinux,r/linuxmasterrace]
      * [x] Unix <unix>                               - [unix@lobsters]
    * [@] [Software Development]
  * [x] CSApplications [<csa>]
    * [x] Hacking <hacking>                                                                            -[r/hacking,r/HowToHack,r/Hacking_Tutorials,r/hackers]
    * [x] Robotics(0)  <robotics>                                                                      -[r/robotics,r/arduino]
    * [x] AR-VR <arvr>                                                                                 -[r/virtualreality,r/augmentedreality]
    * [x] IOT <iot>                                                                                    -[r/IOT]
    * [x] Computer Vision <compvision>                                                                 -[r/computervision,r/opencv]
    * [x] Image Processing <imgprocess>                                                                -[r/imageprocessing,r/dip]
    * [x] Data Mining <datamine>                      -   .....                                        -[r/datamining,r/textdatamining]
    * [x] MachineLearning  [<ml>]
      *  [x] GeneralML <gen_ml>                               -  .....                                     -[r/MachineLearning,r/learnmachinelearning,r/ResearchML,r/neuralnetworks]
      *  [x] Artificial Neural Networks <ann>                                                            -[r/neuralnetworks,r/NeuralNetwork]
      *  [x] Deep Learning <dl>                                                                          -[r/neuralnetworks,r/deeplearning,r/DeepLearningPapers,r/deeplearners]
    * [x] DataScience [<ds>]                               -  .....                                        -[r/datascience,r/learndatascience]
      * [x] General Data Science <gen_dS>                               -  .....                                     -[r/datascience,r/learndatascience]
      * [x] Database(0) <database>                           - [databases@lobsters]                      -[r/Database]
      * [x] Datasets <dataset>                             -  ......                                     -[r/datasets]
      * [x] Statistics <statistics>                                                                      -[r/statistics,r/AskStatistics]
      * [x]  R Language<rlang>                                                                           -[r/Rlanguage,r/rstats]
      * [x]  Matlab <matlab>                                                                             -[r/matlab]
      * [x]  DS Tools [<ds_tool>]
        * [x] Scala <scala>                                                                              -[r/scala]
        * Pandas                                                                         
        * Matplotlib 
        * NLTK 
        * [x] Scikit-learn <scikit>                                                                      -[r/scikit_learn]
        * TensorFlow <tf>       
        * [x] Jupyter Notebook <jupyternote>                                                               -[r/JupyterNotebooks]
      *  [x] Kaggle <kaggle>                                                                              -[r/kaggle]
      *  [x] Data Cleaning <datacleaning>                                                                 -[r/datacleaning]
      * [x] NLP <nlp>                                                                                    -[r/NLP,r/LanguageTechnology]
        * Chatbot
    * [x] DataEngineering [<de>]
      * [x] [[<database>]]                                      - [databases@lobsters]                     -[r/Database]
      * [x] BigData [<bigdata>]
        * [x] General Big Data <gen_bigdata>                -  ......                                     -[r/bigdata]
        * [x] Apache Spark <spark>                                                                       -[r/apachespark]
        * [x] Hadoop <hadoop>                                                                            -[r/hadoop]
    * [x] DataVisualisation  [<data_visn>]
      * [x] General Data Visualisation <gen_datavis>          - [visualization@lobsters,]                   -[r/visualization,r/dataisbeautiful]
      * [x] Tableau <tableau>                                                                         -[r/tableau]
      * [x] Microsoft Excel <excel>                                                                   -[r/excel,r/ExcelTips]
    * [x] Artificial Intelligence  <ai>                                       - [ai@lobsters]                               -[r/artificial,r/ArtificialInteligence]
* Programming   / Software Development <prog>
  * General Programming <gen_prog>                      - [programming@lobsters]                      -[r/programming,r/coding,r/softwaredevelopment(0),r/SoftwareEngineering]
  * [x] Languages&Frameworks [<lng_n_frmwrk>]
    * [x] Languages [<lng>]
      * [x] Programming Languages  <proglng>              -  .......                                    -[r/ProgrammingLanguages,r/learnprogramming,r/functionalprogramming]
      * [x] Programming Language Theory <plt>             - [plt@lobsters]
      * [x] Assembly Language <asm>                     - [assembly@lobsters,]                        -[r/asm]
      * [x] C <c>                                     - [c@lobsters,]                               -[r/C_Programming,r/c_language]
      * [x] C++  <cpp>                                - [c++@lobsters,]                             -[r/cpp,r/Cplusplus]
      * [x] Golang <golang>                           - [go@lobsters]                               -[r/golang]
      * [x] Python <python>                           - [python@lobsters,]                          -[r/Python]
      * [x] Scala <scala>                             - [scala@lobsters,]                           -[r/scala]
      * [x] Elixir <elixir>                           - [elixir@lobsters]
      * [x] Elm <elm>                                 - [elm@lobsters]
      * [x] Erlang  <erlang>                          - [erlang@lobsters,]                          -[r/erlang]
      * [x] Fortran <fortran>                         - [fortran@lobsters]
      * [x] Haskell <haskell>                         - [haskell@lobsters,]                         -[r/haskell]
      * [x] Java <java>                               - [java@lobsters,]                            -[r/java]
      * [x] Javascript <js>                           - [javascript@lobsters,]                      -[r/javascript]
      * [x] Lisp <lisp>                               - [lisp@lobsters,]                            -[r/lisp]
      * [x] Perl <perl>                               - [perl@lobsters]                             -[r/perl]
      * [x] PHP <php>                                 - [php@lobsters,]                             -[r/PHP]
      * [x] Ruby <ruby>                               - [ruby@lobsters,]                            -[r/ruby]
      * [x] Rust <rust>                               - [rust@lobsters]                             -[r/rust]
      * [@] C#                                        - [dotnet@lobsters, ...]
      * [@] F#                                        - [dotnet@lobsters, ...]
      * [x] .NET <dotnet>                             - [dotnet@lobsters,]                          -[r/dotnet]
      * [x] Kotlin  <kotlin>                          -  .....                                      -[[r/Kotlin]
      * [x] HTML <html>                               - [css@lobsters, ...]                         -[r/HTML,/r/html5]
      * [x] CSS  <css>                                - [css@lobsters]                              -[r/css]
  * [x] Frameworks  [<frmwrk>]         
    * [x] Ruby on Rails <ror>                           - .....                                       -[r/rails]
    * [x] Django  <django>                              - .....                                       -[r/django]
    * [x] ReactJS <reactjs>                             - .....                                       -[r/reactjs]
    * [x] NodeJS <nodejs>                               - [nodejs@lobsters,r/node]
  * [x] ProgrammingTools [<prog_tools>]
    * [x] Git & VCS <git>                               - [vcs@lobsters]                              -[r/git,r/github,r/gitlab]
    * [x] Virtualization <virtualn>                     - [virtualization@lobsters]                   -[r/virtualization]
    * [x] Web Browsers <browser>                        - [browsers@lobsters]                         -[r/browsers]
    * [x] AWS <aws>                                     - .....                                       -[r/aws,r/AWS_cloud]
    * [x] Azure <azure>                                                                               -[r/AZURE,r/azuredevops]  
    * [x] Kubernetes <k8s>                                                                            -[r/kubernetes,r/k8s]  
    * [x] Docker <docker>                                                                             -[r/docker]
    * [x] GCP <gcp>                                                                                   -[r/GCP]                  
    * [x] TextEditors [<txt_edit>]
      * [x] Editors <editor>                              - [emacs@lobsters,...]
      * [x] Vim <vim>                                                                                 -[r/vim,r/neovim,r/vim_magic]
      * [x] Emacs <emacs>                                                                             -[r/emacs]
  * [x] AppDevelopment [<appdev>]
    * [x] General App Development <gen_appdev>              - [mobile@lobsters]                          -[r/appdev,r/AppDevelopment]
    * [x] iOS Dev <iosdev>                                  - [ios@lobsters]                             -[r/iosdev,r/iOSProgramming]
    * [x] Android Dev <androiddev>                          - [android@lobsters]                         -[r/androiddev]
  * [x] DevOps [<devops>]
    * [x] General DevOps <gen_devops>                        - [devops@lobsters]                           -[r/devops]
    * [x] [AWS](1) 
    * [x] [Azure](1)
    * [x] [Kubernetes](1)
    * [x] [Docker](1)
    * [x] [GCP](1)
  * [x] Security  [<security>]
    * [x] Information Security <infosec>               - [security@lobsters]                         -[r/netsec]
    * [x] Computer Security <compsec>                   - .....                                       -[[r/compsec]
    * [x] Web Security <websec>                         - .....                                       -[[r/websec]
    * [x] Privacy <privacy>                             - [privacy@lobsters]                          -[r/privacy]
    * [x] Cryptography(1)<crypto_cse>                   - [crypto@lobsters,]                          -[r/crypto,r/cryptography]
  * [@] System Design
  * [x] Design [<design>]
    * [x] Graphix Design  <graphix>                     - [design@lobsters]
    * [x] Computer Graphics <compgphix>                 - [graphics@@lobsters,]                       -[r/computergraphics]
    * [x] Web Design <webdes>                           - .....                                       -[r/web_design]
    * [x] UI <ui>                                                                                     -[r/UI_Design,r/UI_programming]
    * [x] UX <ux>                                                                                     -[r/UXDesign,r/UXResearch,r/UX_Design]
  * [x] Database <db>                                    - .....                                    -[r/Database]
      * SQL
      * MongoDB
      * Cassandra
      * DashDB 
  * [x] Web Development <webd>                       - [web@lobsters,]                            -[r/webdev]
  * [@] Software Releases                            - [release@lobsters,announce@lobsters]
  * [@] Debugging                                    - [debugging@lobsters]
  * [x] Software Testing <sdt>                      - [testing@lobsters]                         -[r/softwaretesting]
  * [@] Scaling                                     - [scaling@lobsters]
  * [x] System Performance & Optimisation <system>  - [performance@lobsters,]                     -[r/systems]
  * [x] Development Practices <devpract>            - [practices@lobsters,]                       -[r/tinycode,r/softwaredevelopment(2)]
  *  Acrhitecture
  * Product Management 
  * [x] API <api>                                       - [api@lobsters]                              -[r/api]
  * [x] Game Dev <gamedev>                         - [games@lobsters,]                           -[r/gamedev]
  * [x] Coding Challanges<codingchlg> (0)               - .....                                       -[r/programmingchallenges]
  * [@] Law, patents, and licensing(+2)                 - [law@lobsters]
  * [x] Open Source (0) <opensrc>                       - .....                                       -[[r/opensource]
  * [x] Free Software <freesoft>                        -  ....                                       -[r/freeculture,r/freesoftware]
  * [x] [[<os>]]
  * [x] Technical Queries <prog_query>(0)               - .....                                     -[r/AskComputerScience,askHN]
* [x] Career [<career>]
  * [x] Jobs <jobs>                                    - [job@lobsters]                               -[r/forhire]
  * [x] Career Queestions<carr_query>                    - .....                                      -[r/cscareerquestions]
  * [@] Openings
  * [x] Interview Preparation <interviewprep>                                                          -[r/interviewpreparations,r/csinterviewproblems]
  * [x] Interview Experiences <interviewexp>                                                           -[r/interviews]
  * [x] [Coding Challanges](1)    
* [x] Social [<social>] (or Community) 
  * [x] Tech News <technews>                       - .....                                            - [r/technology,r/TrueReddit,r/wikipedia,r/geek]                          
  * [x] Technical discussions <tech_discuss>                 - .....                                  - [tellHN]
  * [x] Technical Queries <tech_query>(1)                       - .....                               - [r/AskComputerScience(1),askHN(1)]
  * [x] Technical communities and culture <community>   -[culture@lobsters]                           - [r/skeptic]                     
  * Social Philosophy                                   - ......                                      - [r/Agorism]
  * Rants(rant@lobsters)
  * Stories about particular persons <person>       - [person@lobsters]
  * Interviews -->
  * [x] Blogs <tech_blog>                                                                             - [r/blog]
  * Education                                            - [education@lobsters] 
  * Travel/Geography 
  * [x] Law, patents, and licensing <tech_law>          - [law@lobsters]                              -[r/COPYRIGHT,r/noip]
  * Politics 
  * Intellectual Property Laws                           - ...                                         - [r/noip] 
  * [x] Cognitive Science <cogsci>                      - [cogsci@lobsters]                           - [r/cognitivescience]
  * [x] Torrents <torrent>                                                                            - [r/torrents]
  * [x] Reading&Writing [<read_n_write>]
    * Art                                            - [art@lobsters]  
    * [x] Books  <book>                                 - [book@lobsters]                             - [r/books,r/scifi,r/bookclub]
    * [x] Writing <write>                                                                           - [r/writing]
    * [x] Philosophy(general)  <phil>  ...              - .....                                       - [r/atheism,r/philosophy]
    * [x] History <history>                             - [historical@lobsters]                       - [r/history,r/AskHistorians]
* 6. Business [<business>]
  * [x] Gen. Business <gen_business>                        - .....                                       - [r/business,r/Flipping]
  * [x] Startup  <startup>                              - .....                                       - [launchHN,PH,r/startups,r/Entrepreneur,r/digitalnomad]
  * [x] Freelancing <freelance>                                                                       - [r/freelance,r/Upwork]
  * [x] Saas <saas>                                                                                   - [r/SaaS]
  * [x] Side Project <sideproj>                         - ......                                      - [showHN,r/SideProject]
  * [x] Marketing & Advertising <market>               - .....                                        - [r/marketing]
  * [x] SEO <seo>                                  - .....                                        - [r/SEO,r/bigseo,r/SEO_Digital_Marketing]
  * [x] [[<opensrc>]](1)                                 - .....                                        - [r/opensource]
* [x] Science [<science>]
  * [x] General Science <gen_science>                             - [science@lobsters]                    - [r/science]
  * [x] Scinece Queries <sci_query>                                                                   - [r/askscience,r/AskPhysics]
  * [x] Chemistry <chemistry>                                                                         - [r/chemistry]
  * [x] Biology <biology>                                                                             - [r/biology]
  * [x] Medicine <medicine>                                                                           - [r/medicine]
  * [x] Neuroscience <neuroscience>                                                                   - [r/neuroscience]
  * [x] Geology <geology>                                                                             - [r/geology]
  * [x] Ecology/Environment <env>                                                                      - [r/environment]
  * Psychology                                                                            
  * [x] Health <health>                                                                                - [r/Health]
  * [x] Physics [<physica>]
    * [x] Gen. Physics <gen_physics>                                                                      - [r/Physics]
    * [x] Astronomy, Astrophysics, space <astro>                                                      - [r/space,r/aerospace]  #TODO: add more for 'astro' part
    * [x] Quantum Physics <quantum>                                                                   - [r/quantum,r/QuantumPhysics]
    * [x] Nuclear Physics <nuclear>                                                                   - [r/energy]
    * [x] Fluid Mechanics <fluid_mech>                                                                - [r/FluidMechanics]
* [x] Engineering  [<engg>]
  * [x] Gen. Engineering <gen_engg>                                                                         - [r/engineering]   
  * [x] Electronics Engg <engg_ece>                                                                         - [r/electronics,r/ECE]
  * [x] Electrical Engg <engg_electric>                                                                - [r/ElectricalEngineering]
  * [x] Engineering Queries <engg_query>                                                               - [r/AskEngineers,r/LearnEngineering,r/AskElectronics]
  * [x] Mechanical Engineering <engg_mech>                                                        - [r/MechanicalEngineering]
  * [x] Engineering Students <engg_student>                                                            - [r/EngineeringStudents]
  * [x] Aviation, Rockets & aerodynamics <rocket>                                                      - [r/rocketry,r/aviation,r/nasa,r/spacex,r/aerodynamics]
  * [x] Structural Engineering <engg_struct>                                                           - [r/StructuralEngineering]
  * [x] [[<robotics>]](1)   
  * [x] 3D Printing <3dprint>                                                                          - [r/3Dprinting]
* [x] Mathematics [<maths>]
  * [x] Gen.Mathematics <gen_maths>                           - [math@lobsters,]                            - [r/math,r/mathematics]
  * [@] Geometry
  * [x] Calculus <calculus>                                                                           -[r/calculus,r/DifferentialEquations]
  * [x] Algebra <algebra>                                                                             -[r/Algebra] 
  * [x] [<gametheory>]
  * [x] Graph Theory <graphtheory>                                                                    -[r/GraphTheory]
  * [x] [[<logic>]](1)                                       - .....                                       -[r/logic(1)]
  * [x] [[<disco>]](1)    
  * [x] [[<statistics>]](1-R_part)                          - .....                                       - [r/statistics]
  * [x] [[<crypto_cse>]](2)                               - [crypto@lobsters,]                          -[r/crypto,r/cryptography]
* [x] Finance&Economics [<fin_eco>]
  * [x] Economics <economics>                                                                         -[r/Economics,r/economy]
  * [x] Finance & Personal Finance  <finance>                              - [finance@lobsters]                          -[r/finance,r/personalfinance]
  * Money
  * [x] Accounting <accounting>                                                                       -[r/Accounting]
  * [x] Investment <invest>                                                                           -[r/invest,r/investing]
  * [x] Blockchain [<blockchain>]
    * [x] Gen. Blockchain <gen_blockchain>                                                                       -[r/BlockchainStartups]
    * [x] Cryptocurrencies <crypto_fin>                   - [cryptocurrencies@lobsters]                 -[r/CryptoCurrency]
    * [x] Bitcoin <bitcoin>                             - .....                                       -[r/Bitcoin,r/BitcoinBeginners,r/bitcointrading,r/BitcoinDiscussion]


"""

tags = re.findall('<(.*?)>', text)

for tag in tags:
    print('"{}",'.format(tag))
